package com.wordpress.williamcosta303.jogo;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

public class CartasWindow extends javax.swing.JFrame {
        DecimalFormat df = new DecimalFormat("##0.00");
        VCartas cred = new VCartas();
        Cartas jog1 = new Cartas();
        Log log = new Log();
        
        
    public CartasWindow() {
        initComponents();
        this.setResizable(false); // Impede a alteração do tamanho da GUI
        jog1.cartaInicial = jog1.geraCarta(); // Gera uma carta inicial
        jog1.naipeInicial = jog1.geraNaipe(); // Gera um naipe inicial
        this.lCartaAtual.setText(jog1.mostraCarta(jog1.cartaInicial) + jog1.naipeInicial);
        jog1.regras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        bApostarMais = new javax.swing.JButton();
        bApostarMenos = new javax.swing.JButton();
        lCartaAtual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tSaldoAtual = new javax.swing.JLabel();
        lSaldo = new java.awt.Label();
        bDesistir = new javax.swing.JButton();
        tAposta = new javax.swing.JLabel();
        lAposta = new javax.swing.JLabel();
        bMenos = new javax.swing.JButton();
        bMais = new javax.swing.JButton();
        tEndereco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        titulo.setFont(new java.awt.Font("DilleniaUPC", 1, 48)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("High/Low card game");

        bApostarMais.setText("Bet Higher");
        bApostarMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApostarMaisActionPerformed(evt);
            }
        });

        bApostarMenos.setText("Bet Lower");
        bApostarMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bApostarMenosActionPerformed(evt);
            }
        });

        lCartaAtual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lCartaAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCartaAtual.setText(jog1.mostraCarta(jog1.cartaInicial) + jog1.naipeInicial);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Current card:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tSaldoAtual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tSaldoAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tSaldoAtual.setText("Current balance:");

        lSaldo.setAlignment(java.awt.Label.CENTER);
        lSaldo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lSaldo.setText("$" + df.format(jog1.saldoAtual));

        bDesistir.setText("Give up");
        bDesistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDesistirActionPerformed(evt);
            }
        });

        tAposta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tAposta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tAposta.setText("Bet:");

        lAposta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lAposta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAposta.setText("$" + df.format(jog1.aposta));

        bMenos.setText("-");
        bMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenosActionPerformed(evt);
            }
        });

        bMais.setText("+");
        bMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMaisActionPerformed(evt);
            }
        });

        tEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tEndereco.setText("williamcosta303.wordpress.com");
        tEndereco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tEnderecoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lCartaAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tSaldoAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bApostarMais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bDesistir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bApostarMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lAposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tAposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bMais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lCartaAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bApostarMais)
                        .addGap(7, 7, 7)
                        .addComponent(bApostarMenos))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lAposta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bMais)
                            .addComponent(bMenos)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tSaldoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(bDesistir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(tEndereco))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bApostarMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApostarMaisActionPerformed
        log.botaoPressionado("apostar mais");
        jog1.apostarMais();
        this.lCartaAtual.setText(jog1.mostraCarta(jog1.cartaInicial) + jog1.naipeInicial);
        this.lSaldo.setText("$" + df.format(jog1.saldoAtual));
        if (jog1.saldoAtual >= 200 && !jog1.cheater){
            log.vitoria(true, false);
            JOptionPane.showMessageDialog(null, jog1.nomeJogador + " won with a balance of $" + df.format(jog1.saldoAtual) + "\nGame over!");
            int novoJogo = JOptionPane.showConfirmDialog(null, "Would you like to play again?", "New game", JOptionPane.YES_NO_OPTION);
            if (novoJogo == JOptionPane.YES_OPTION){
                log.msgGenerica("Novo jogo iniciado!");
                this.novoJogo();
            } else {
                cred.creditos();
                log.encerrar();
                System.exit(0);
            }
        } else if (jog1.saldoAtual >= 200 && jog1.cheater){
            log.vitoria(true, true);
            JOptionPane.showMessageDialog(null, jog1.nomeJogador + " CHEATED with a balance of $-9001,00 :(\nGame over!");
            int novoJogo = JOptionPane.showConfirmDialog(null, "Would you like to play again?", "New game", JOptionPane.YES_NO_OPTION);
            if (novoJogo == JOptionPane.YES_OPTION){
                log.msgGenerica("Novo jogo iniciado!");
                this.novoJogo();
            } else {
                cred.creditos();
                log.encerrar();
                System.exit(0);
            }
        } else if (jog1.saldoAtual < -50){
            log.vitoria(false, false);
            JOptionPane.showMessageDialog(null, jog1.nomeJogador + " went bankrupt with a balance of $" + df.format(jog1.saldoAtual) + "\nGame over!");
            int novoJogo = JOptionPane.showConfirmDialog(null, "Would you like to play again?", "New game", JOptionPane.YES_NO_OPTION);
            if (novoJogo == JOptionPane.YES_OPTION){
                log.msgGenerica("Novo jogo iniciado!");
               this.novoJogo();
            } else {
                cred.creditos();
                log.encerrar();
                System.exit(0);
            }
        } else {
            // Nothing
        }
    }//GEN-LAST:event_bApostarMaisActionPerformed

    private void bApostarMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bApostarMenosActionPerformed
        log.botaoPressionado("apostar menos");
        jog1.apostarMenos();
        this.lCartaAtual.setText(jog1.mostraCarta(jog1.cartaInicial) + jog1.naipeInicial);
        this.lSaldo.setText("$" + df.format(jog1.saldoAtual));
        if (jog1.saldoAtual >= 200 && !jog1.cheater){
            log.vitoria(true, false);
            JOptionPane.showMessageDialog(null, jog1.nomeJogador + " won with a balance of $" + df.format(jog1.saldoAtual) + "\nGame over!");
            int novoJogo = JOptionPane.showConfirmDialog(null, "Would you like to play again?", "New game", JOptionPane.YES_NO_OPTION);
            if (novoJogo == JOptionPane.YES_OPTION){
                log.msgGenerica("Novo jogo iniciado!");
                this.novoJogo();
            } else {
                cred.creditos();
                log.encerrar();
                System.exit(0);
            }
        } else if (jog1.saldoAtual >= 200 && jog1.cheater){
            log.vitoria(true, true);
            JOptionPane.showMessageDialog(null, jog1.nomeJogador + " CHEATED with a balance of $-9001,00 :(\nGame over!");
            int novoJogo = JOptionPane.showConfirmDialog(null, "Would you like to play again?", "New game", JOptionPane.YES_NO_OPTION);
            if (novoJogo == JOptionPane.YES_OPTION){
                log.msgGenerica("Novo jogo iniciado!");
                this.novoJogo();
            } else {
                cred.creditos();
                log.encerrar();
                System.exit(0);
            }
        } else if (jog1.saldoAtual < -50){
            log.vitoria(false, false);
            JOptionPane.showMessageDialog(null, jog1.nomeJogador + " went bankrupt with a balance of $" + df.format(jog1.saldoAtual) + "\nGame over!");
            int novoJogo = JOptionPane.showConfirmDialog(null, "Would you like to play again?", "New game", JOptionPane.YES_NO_OPTION);
            if (novoJogo == JOptionPane.YES_OPTION){
                log.msgGenerica("Novo jogo iniciado!");
                this.novoJogo();
            } else {
                cred.creditos();
                log.encerrar();
                System.exit(0);
            }
        } else {
            // Nothing
        }
    }//GEN-LAST:event_bApostarMenosActionPerformed

    private void bDesistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDesistirActionPerformed
        log.botaoPressionado("desistir");
        int desistencia = JOptionPane.showConfirmDialog(
                                null, // Pede confirmação
                                "Current balance: $" + df.format(jog1.saldoAtual)
                                + "\nAre you sure you want to give up?",
                                "Giving up", JOptionPane.YES_NO_OPTION);
                        if (desistencia == JOptionPane.YES_OPTION) { // Se sim
                            JOptionPane.showMessageDialog(null, jog1.nomeJogador // Exibe
                                    // o
                                    // saldo
                                    // final
                                    + " gave up with a balance of: $"
                                    + df.format(jog1.saldoAtual) + "\nGame over!");
                           int sair2 = JOptionPane.showConfirmDialog(null, "Would you like to play again?", "New game", JOptionPane.YES_NO_OPTION);
                           if (sair2 == JOptionPane.YES_OPTION){
                               this.novoJogo();
                           } else {
                               cred.creditos();
                               log.encerrar();
                               System.exit(0);
                           }
                        }
    }//GEN-LAST:event_bDesistirActionPerformed

    private void bMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenosActionPerformed
        log.botaoPressionado("aumentar aposta");
        if (jog1.aposta > 3.5 && jog1.aposta != 50){
            jog1.aposta-=0.5;
            this.lAposta.setText("$" + df.format(jog1.aposta));
        } else if (jog1.aposta > 3.5 && jog1.aposta == 50) {
            jog1.aposta = 10;
            this.lAposta.setText("$" + df.format(jog1.aposta));
        } else {
            JOptionPane.showMessageDialog(null, "Bet already at minimum!");
            log.msgGenerica("Erro! Aposta no mínimo!");
        }
    }//GEN-LAST:event_bMenosActionPerformed

    private void bMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMaisActionPerformed
        log.botaoPressionado("diminuir aposta");
        if (jog1.aposta < 10 && jog1.aposta != 0.5 ){
            jog1.aposta+=0.5;
            this.lAposta.setText("$" + df.format(jog1.aposta));
         } else if (jog1.aposta < 10 && jog1.aposta == 0.5){
             jog1.aposta = 3.5;
             this.lAposta.setText("$" + df.format(jog1.aposta));
         } else {
             JOptionPane.showMessageDialog(null, "Bet already at maximum!");
             log.msgGenerica("Erro! Aposta no máximo!");
         }
    }//GEN-LAST:event_bMaisActionPerformed

    private void tEnderecoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tEnderecoMouseClicked
        log.botaoPressionado("cheats");
        jog1.digitarCheats();
        log.returnCheats(jog1.cheats);
        this.atualizarTextos();
    }//GEN-LAST:event_tEnderecoMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        log.encerrar();
    }//GEN-LAST:event_formWindowClosing

    public void novoJogo(){
        boolean temNome = false;
        while(!temNome){
        try{
        jog1.nomeJogador = JOptionPane.showInputDialog("Type in your name:", cred.randNomePadrao());
            if (jog1.nomeJogador.length() <= 3 || jog1.nomeJogador.length() > 20
                        || jog1.nomeJogador.equals("    ") || jog1.nomeJogador.equals("1234")
                        || jog1.nomeJogador.equals("") || jog1.nomeJogador.length() == 0) {
                    do {
                        jog1.nomeJogador = JOptionPane
                                .showInputDialog("Invalid name! (Min: 4 characters Max: 20 characters)\nType in your name:");
                    } while (jog1.nomeJogador.length() <= 3 || jog1.nomeJogador.length() > 20
                            || jog1.nomeJogador.equals("    ") || jog1.nomeJogador.equals("1234")
                            || jog1.nomeJogador.length() == 0);
                }
        jog1.aposta = 5;
        jog1.saldoAtual = 50;
        jog1.cartaInicial = jog1.geraCarta();
        jog1.naipeInicial = jog1.geraNaipe();
        jog1.cheater = false;
        this.atualizarTextos();
        temNome = true;
        } catch (NullPointerException erroWinFechada) {
            log.erroWinFechada(erroWinFechada);
            JOptionPane.showMessageDialog(null, "The game needs a name before we begin!");
            }
        }
    }
    
    public void atualizarTextos(){
        this.lCartaAtual.setText(jog1.mostraCarta(jog1.cartaInicial) + jog1.naipeInicial);
        this.lSaldo.setText("$" + df.format(jog1.saldoAtual));
        this.lAposta.setText("$" + df.format(jog1.aposta));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartasWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bApostarMais;
    private javax.swing.JButton bApostarMenos;
    private javax.swing.JButton bDesistir;
    private javax.swing.JButton bMais;
    private javax.swing.JButton bMenos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lAposta;
    private javax.swing.JLabel lCartaAtual;
    private java.awt.Label lSaldo;
    private javax.swing.JLabel tAposta;
    private javax.swing.JLabel tEndereco;
    private javax.swing.JLabel tSaldoAtual;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
